/**
 * Shared primitives for every domain contract.
 * All timestamps are UTC ISO 8601 strings (e.g. "2026-08-26T21:00:00.000Z").
 */

/** Internal, stable UUID v4 identifier generated by MATN (never an Azure id). */
export type Uuid = string;

/** UTC ISO 8601 timestamp. */
export type IsoTimestamp = string;

/** Calendar date without time, "YYYY-MM-DD". */
export type IsoDate = string;

/** IANA time zone name, e.g. "Africa/Cairo". */
export type TimeZone = string;

/** Bilingual label. Arabic is primary, English is secondary. */
export interface Localized {
  readonly ar: string;
  readonly en: string;
}

/** JSON-safe value union — replaces `any` for unmapped Azure fields. */
export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
/** Bag of custom / process-specific Azure fields keyed by Azure reference name. */
export type CustomFields = Readonly<Record<string, JsonValue>>;

/** Tenant scoping applied to every customer-owned record. */
export interface TenantScoped {
  readonly tenantId: Uuid;
}

/** Row bookkeeping shared by all persisted entities. */
export interface RecordMeta {
  readonly createdAt: IsoTimestamp;
  readonly updatedAt: IsoTimestamp;
  /** Last successful sync that touched this row; null for locally created rows. */
  readonly lastSyncedAt: IsoTimestamp | null;
  /** Soft-delete marker: entity no longer present in Azure DevOps. */
  readonly deletedAt: IsoTimestamp | null;
}

/** Whether a value could be computed, and why not. */
export type ValueAvailability =
  "available" | "missing_source" | "not_applicable" | "insufficient_history";

/** A numeric measure that may be legitimately unavailable. */
export interface Measure {
  readonly value: number | null;
  readonly availability: ValueAvailability;
  /** Share of required inputs that were present, 0..1. */
  readonly completeness: number;
}

/** Freshness classification for one data domain. */
export type FreshnessStatus = "current" | "delayed" | "stale" | "unavailable" | "partial";

export interface DomainFreshness {
  readonly status: FreshnessStatus;
  readonly lastSyncedAt: IsoTimestamp | null;
  readonly ageMinutes: number | null;
}

/** Freshness is tracked per source domain, never as a single global claim. */
export interface FreshnessReport {
  readonly workItems: DomainFreshness;
  readonly capacity: DomainFreshness;
  readonly repositories: DomainFreshness;
  readonly pullRequests: DomainFreshness;
  readonly builds: DomainFreshness;
  readonly deployments: DomainFreshness;
  readonly tests: DomainFreshness;
  /** Worst status across the domains above. */
  readonly overall: FreshnessStatus;
}

/** Provenance of any value shown in the UI. */
export type DataOrigin =
  "azure_source" | "normalized" | "history" | "calculated" | "ai_generated" | "mock";

/** Versioned calculation stamp so historical values stay explainable. */
export interface CalculationStamp {
  readonly calculationVersion: string;
  readonly calculatedAt: IsoTimestamp;
  readonly origin: DataOrigin;
}

/** Health language shared with the approved Phase 1 UI. */
export type HealthStatus = "healthy" | "atRisk" | "critical" | "neutral" | "watch";
export type Severity = "critical" | "high" | "medium" | "watch";

/* ------------------------------------------------------------------ */
/* Source lifecycle (Phase 2.1)                                        */
/* ------------------------------------------------------------------ */

/**
 * Lifecycle of a record relative to its Azure DevOps source.
 * "deleted" and "inaccessible" are never conflated: a 404 (after a second
 * verification) means deleted, a 403 means access was revoked.
 */
export type SourceStatus = "active" | "deleted" | "inaccessible" | "unknown";

/** Applied to every entity that mirrors an Azure DevOps object. */
export interface SourceTracked {
  readonly sourceStatus: SourceStatus;
  /** Convenience flag: true only when sourceStatus === "deleted". */
  readonly isDeleted: boolean;
  /** When the object was confirmed missing at the source (after verification). */
  readonly deletedAtSource: IsoTimestamp | null;
  /** Last sync in which the object was observed as present and readable. */
  readonly lastSeenAt: IsoTimestamp | null;
  /** When reads started failing with 403 / scope loss. */
  readonly accessRevokedAt: IsoTimestamp | null;
}

/** Result of the two-step verification that precedes any tombstone. */
export interface SourceDisappearanceCheck {
  readonly firstMissingAt: IsoTimestamp;
  readonly verifiedAt: IsoTimestamp | null;
  readonly httpStatus: number | null;
  readonly conclusion: "deleted" | "inaccessible" | "still_present" | "undetermined";
  /** Set when the conclusion is "undetermined"; a data-quality issue is raised. */
  readonly undeterminedReason: string | null;
}

/** Tenant-configurable retention window, in days; null means indefinite. */
export interface RetentionRule {
  readonly key:
    | "work_item_revisions"
    | "daily_project_snapshots"
    | "daily_iteration_snapshots"
    | "daily_team_snapshots"
    | "daily_member_snapshots"
    | "raw_payload_cache"
    | "sync_run_details"
    | "audit_events"
    | "copilot_answers";
  readonly defaultDays: number | null;
  readonly configuredDays: number | null;
  /** Records under legal hold are never removed, whatever the window says. */
  readonly legalHoldActive: boolean;
}
