/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BacklogRouteImport } from './routes/backlog'
import { Route as BoardRouteImport } from './routes/board'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as EngineeringRouteImport } from './routes/engineering'
import { Route as HierarchyRouteImport } from './routes/hierarchy'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as StuckRouteImport } from './routes/stuck'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSettingsAzureRouteImport } from './routes/_authenticated/settings.azure'
import { Route as ApiPublicCronTickRouteImport } from './routes/api/public/cron/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRoute = BacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringRoute = EngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const HierarchyRoute = HierarchyRouteImport.update({
  id: '/hierarchy',
  path: '/hierarchy',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const StuckRoute = StuckRouteImport.update({
  id: '/stuck',
  path: '/stuck',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsAzureRoute =
  AuthenticatedSettingsAzureRouteImport.update({
    id: '/settings/azure',
    path: '/settings/azure',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronTickRoute = ApiPublicCronTickRouteImport.update({
  id: '/api/public/cron/tick',
  path: '/api/public/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/backlog': typeof BacklogRoute
  '/board': typeof BoardRoute
  '/delivery': typeof DeliveryRoute
  '/engineering': typeof EngineeringRoute
  '/hierarchy': typeof HierarchyRoute
  '/intelligence': typeof IntelligenceRoute
  '/people': typeof PeopleRoute
  '/stuck': typeof StuckRoute
  '/team': typeof TeamRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings/azure': typeof AuthenticatedSettingsAzureRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/backlog': typeof BacklogRoute
  '/board': typeof BoardRoute
  '/delivery': typeof DeliveryRoute
  '/engineering': typeof EngineeringRoute
  '/hierarchy': typeof HierarchyRoute
  '/intelligence': typeof IntelligenceRoute
  '/people': typeof PeopleRoute
  '/stuck': typeof StuckRoute
  '/team': typeof TeamRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings/azure': typeof AuthenticatedSettingsAzureRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/backlog': typeof BacklogRoute
  '/board': typeof BoardRoute
  '/delivery': typeof DeliveryRoute
  '/engineering': typeof EngineeringRoute
  '/hierarchy': typeof HierarchyRoute
  '/intelligence': typeof IntelligenceRoute
  '/people': typeof PeopleRoute
  '/stuck': typeof StuckRoute
  '/team': typeof TeamRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings/azure': typeof AuthenticatedSettingsAzureRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/auth'
    | '/backlog'
    | '/board'
    | '/delivery'
    | '/engineering'
    | '/hierarchy'
    | '/intelligence'
    | '/people'
    | '/stuck'
    | '/team'
    | '/onboarding'
    | '/settings/azure'
    | '/api/public/cron/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/auth'
    | '/backlog'
    | '/board'
    | '/delivery'
    | '/engineering'
    | '/hierarchy'
    | '/intelligence'
    | '/people'
    | '/stuck'
    | '/team'
    | '/onboarding'
    | '/settings/azure'
    | '/api/public/cron/tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alerts'
    | '/auth'
    | '/backlog'
    | '/board'
    | '/delivery'
    | '/engineering'
    | '/hierarchy'
    | '/intelligence'
    | '/people'
    | '/stuck'
    | '/team'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings/azure'
    | '/api/public/cron/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  BacklogRoute: typeof BacklogRoute
  BoardRoute: typeof BoardRoute
  DeliveryRoute: typeof DeliveryRoute
  EngineeringRoute: typeof EngineeringRoute
  HierarchyRoute: typeof HierarchyRoute
  IntelligenceRoute: typeof IntelligenceRoute
  PeopleRoute: typeof PeopleRoute
  StuckRoute: typeof StuckRoute
  TeamRoute: typeof TeamRoute
  ApiPublicCronTickRoute: typeof ApiPublicCronTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering': {
      id: '/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof EngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hierarchy': {
      id: '/hierarchy'
      path: '/hierarchy'
      fullPath: '/hierarchy'
      preLoaderRoute: typeof HierarchyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stuck': {
      id: '/stuck'
      path: '/stuck'
      fullPath: '/stuck'
      preLoaderRoute: typeof StuckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/azure': {
      id: '/_authenticated/settings/azure'
      path: '/settings/azure'
      fullPath: '/settings/azure'
      preLoaderRoute: typeof AuthenticatedSettingsAzureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/tick': {
      id: '/api/public/cron/tick'
      path: '/api/public/cron/tick'
      fullPath: '/api/public/cron/tick'
      preLoaderRoute: typeof ApiPublicCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsAzureRoute: typeof AuthenticatedSettingsAzureRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsAzureRoute: AuthenticatedSettingsAzureRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  BacklogRoute: BacklogRoute,
  BoardRoute: BoardRoute,
  DeliveryRoute: DeliveryRoute,
  EngineeringRoute: EngineeringRoute,
  HierarchyRoute: HierarchyRoute,
  IntelligenceRoute: IntelligenceRoute,
  PeopleRoute: PeopleRoute,
  StuckRoute: StuckRoute,
  TeamRoute: TeamRoute,
  ApiPublicCronTickRoute: ApiPublicCronTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
